name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        ls ${{ github.workspace }}
        sudo apt update
        sudo apt install -y libkrb5-dev curl xmltv libvlc-dev lirc glutg3-dev libsdl1.2-dev libsdl-image1.2-dev libsdl2-dev
        tar -zxvf fmodstudioapi20107linux.tar.gz
    - name: make installsound
      run: make installsound
    - name: make
      run: tar -zxvf fmodstudioapi20107linux.tar.gz
      run: make installsound
      run: make compile

~