name: C/C++ CI

on: [push]

jobs:
  build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/get-package@v1
    - name: Install dependencies
      with:
        apt-get: libkrb5-dev curl xmltv libvlc-dev lirc glutg3-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libportmidi-dev libical-dev dialog libxrandr-dev
      run: |
        ls ${{ github.workspace }}
        apt update
        apt install -y libkrb5-dev curl xmltv libvlc-dev lirc glutg3-dev libsdl1.2-dev libsdl-image1.2-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libportmidi-dev
    - name: make
      run: |
        ./apt-get_20.04.sh
        make installsound
        make gitcompile

~
