Document: mythtv-controller
Title: Debian mythtv-controller Manual
Author: <insert document author here>
Abstract: This manual describes what mythtv-controller is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mythtv-controller/mythtv-controller.sgml.gz

Format: postscript
Files: /usr/share/doc/mythtv-controller/mythtv-controller.ps.gz

Format: text
Files: /usr/share/doc/mythtv-controller/mythtv-controller.text.gz

Format: HTML
Index: /usr/share/doc/mythtv-controller/html/index.html
Files: /usr/share/doc/mythtv-controller/html/*.html
